// src/lib/components/Avatar.svelte
<script lang="ts">
	let { name = '', size = 36 }: { name?: string; size?: number } = $props();
	const initials = $derived(
		name
			.split(' ')
			.map((p) => p[0])
			.filter(Boolean)
			.slice(0, 2)
			.join('')
			.toUpperCase()
	);
</script>

<span class="avatar" style="--s:{size}px; font-size:{Math.round(size * 0.38)}px">{initials}</span>

<style>
	.avatar {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: var(--s);
		height: var(--s);
		border-radius: var(--radius-pill);
		background: var(--terracotta-100);
		color: var(--terracotta-800);
		font-family: var(--font-display);
		font-weight: var(--weight-semibold);
		flex: none;
	}
</style>

// itaily-design-system/project/components/core/Avatar.jsx
import React from 'react';

/** Circular avatar — initials or image, with optional ring. */
export function Avatar({ name = '', src = null, size = 40, tone = 'accent', ring = false, style = {}, ...rest }) {
  const tones = {
    accent:  { bg: 'var(--terracotta-100)', fg: 'var(--terracotta-700)' },
    neutral: { bg: 'var(--neutral-200)', fg: 'var(--neutral-700)' },
    ink:     { bg: 'var(--neutral-800)', fg: 'var(--paper)' },
  };
  const t = tones[tone] || tones.accent;
  const initials = name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0].toUpperCase())
    .join('');
  return (
    <div
      style={{
        width: size, height: size, borderRadius: '50%',
        display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
        background: t.bg, color: t.fg, overflow: 'hidden', flex: 'none',
        fontFamily: 'var(--font-display)', fontWeight: 'var(--weight-semibold)',
        fontSize: Math.round(size * 0.4), letterSpacing: '-0.02em',
        boxShadow: ring ? '0 0 0 2px var(--surface-card), 0 0 0 4px var(--color-accent)' : 'none',
        ...style,
      }}
      {...rest}
    >
      {src ? <img src={src} alt={name} style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : initials}
    </div>
  );
}
