// itaily-design-system/project/components/core/Badge.jsx
import React from 'react';

/** Compact status / category label. */
export function Badge({ children, tone = 'neutral', variant = 'soft', style = {}, ...rest }) {
  const tones = {
    neutral: { fg: 'var(--neutral-700)', bg: 'var(--neutral-100)', solid: 'var(--neutral-700)' },
    accent:  { fg: 'var(--terracotta-700)', bg: 'var(--terracotta-50)', solid: 'var(--color-accent)' },
    success: { fg: 'var(--status-success-fg)', bg: 'var(--status-success-bg)', solid: 'var(--green-500)' },
    warning: { fg: 'var(--status-warning-fg)', bg: 'var(--status-warning-bg)', solid: 'var(--amber-500)' },
    danger:  { fg: 'var(--status-danger-fg)', bg: 'var(--status-danger-bg)', solid: 'var(--red-500)' },
    info:    { fg: 'var(--status-info-fg)', bg: 'var(--status-info-bg)', solid: 'var(--blue-500)' },
  };
  const t = tones[tone] || tones.neutral;
  const looks = variant === 'solid'
    ? { background: t.solid, color: 'var(--neutral-0)' }
    : variant === 'outline'
    ? { background: 'transparent', color: t.fg, boxShadow: `inset 0 0 0 1.5px ${t.fg}` }
    : { background: t.bg, color: t.fg };
  return (
    <span
      style={{
        display: 'inline-flex', alignItems: 'center', gap: 5,
        fontFamily: 'var(--font-sans)', fontSize: 'var(--text-xs)', fontWeight: 'var(--weight-semibold)',
        letterSpacing: '0.01em', lineHeight: 1,
        padding: '4px 9px', borderRadius: 'var(--radius-sm)', whiteSpace: 'nowrap',
        ...looks, ...style,
      }}
      {...rest}
    >
      {children}
    </span>
  );
}

// src/lib/components/Badge.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	type Tone = 'accent' | 'neutral' | 'success' | 'warning' | 'danger' | 'info';
	type Variant = 'soft' | 'solid' | 'outline';

	let {
		tone = 'neutral',
		variant = 'soft',
		children
	}: { tone?: Tone; variant?: Variant; children: Snippet } = $props();

	// fg / bg / border / solid background per tone, all from Itaily tokens.
	const tones: Record<Tone, { fg: string; bg: string; bd: string; solid: string }> = {
		accent: { fg: 'var(--terracotta-700)', bg: 'var(--terracotta-50)', bd: 'var(--terracotta-200)', solid: 'var(--color-accent)' },
		neutral: { fg: 'var(--text-secondary)', bg: 'var(--neutral-100)', bd: 'var(--border-default)', solid: 'var(--neutral-700)' },
		success: { fg: 'var(--status-success-fg)', bg: 'var(--status-success-bg)', bd: 'var(--status-success-fg)', solid: 'var(--status-success-fg)' },
		warning: { fg: 'var(--status-warning-fg)', bg: 'var(--status-warning-bg)', bd: 'var(--status-warning-fg)', solid: 'var(--status-warning-fg)' },
		danger: { fg: 'var(--status-danger-fg)', bg: 'var(--status-danger-bg)', bd: 'var(--status-danger-fg)', solid: 'var(--status-danger-fg)' },
		info: { fg: 'var(--status-info-fg)', bg: 'var(--status-info-bg)', bd: 'var(--status-info-fg)', solid: 'var(--status-info-fg)' }
	};

	const t = $derived(tones[tone]);
</script>

<span
	class="badge {variant}"
	style="--fg:{t.fg}; --bg:{t.bg}; --bd:{t.bd}; --solid:{t.solid}"
>
	{@render children()}
</span>

<style>
	.badge {
		display: inline-flex;
		align-items: center;
		gap: 4px;
		font-family: var(--font-sans);
		font-size: var(--text-xs);
		font-weight: var(--weight-semibold);
		line-height: 1;
		padding: 4px 9px;
		border-radius: var(--radius-pill);
		white-space: nowrap;
	}
	.soft {
		color: var(--fg);
		background: var(--bg);
		border: 1.5px solid transparent;
	}
	.outline {
		color: var(--fg);
		background: transparent;
		border: 1.5px solid var(--bd);
	}
	.solid {
		color: var(--neutral-0);
		background: var(--solid);
		border: 1.5px solid transparent;
	}
</style>
