// itaily-design-system/project/components/core/Card.jsx
import React from 'react';

/** Surface container with the warm Itaily shadow & border treatment. */
export function Card({ children, elevation = 'sm', padding = 'md', interactive = false, style = {}, ...rest }) {
  const pads = { none: 0, sm: 'var(--space-4)', md: 'var(--space-5)', lg: 'var(--space-6)' };
  const shadows = {
    flat: 'none',
    xs: 'var(--shadow-xs)',
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  };
  return (
    <div
      style={{
        background: 'var(--surface-card)',
        border: '1.5px solid var(--border-default)',
        borderRadius: 'var(--radius-lg)',
        boxShadow: shadows[elevation] ?? shadows.sm,
        padding: pads[padding] ?? pads.md,
        transition: 'box-shadow var(--duration-normal) var(--ease-out), transform var(--duration-normal) var(--ease-out)',
        cursor: interactive ? 'pointer' : 'default',
        ...style,
      }}
      onMouseEnter={interactive ? (e) => { e.currentTarget.style.boxShadow = 'var(--shadow-md)'; e.currentTarget.style.transform = 'translateY(-2px)'; } : undefined}
      onMouseLeave={interactive ? (e) => { e.currentTarget.style.boxShadow = shadows[elevation] ?? shadows.sm; e.currentTarget.style.transform = 'translateY(0)'; } : undefined}
      {...rest}
    >
      {children}
    </div>
  );
}

// src/lib/components/Card.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	let {
		padding = 'md',
		elevation = 'sm',
		source = false,
		interactive = false,
		children,
		class: klass = ''
	}: {
		padding?: 'none' | 'sm' | 'md' | 'lg';
		elevation?: 'flat' | 'xs' | 'sm' | 'md' | 'lg';
		/** Adds the 3px terracotta left-border that marks a primary-source panel. */
		source?: boolean;
		interactive?: boolean;
		children: Snippet;
		class?: string;
	} = $props();

	const pads = { none: '0', sm: 'var(--space-4)', md: 'var(--space-5)', lg: 'var(--space-6)' };
	const shadows = {
		flat: 'none',
		xs: 'var(--shadow-xs)',
		sm: 'var(--shadow-sm)',
		md: 'var(--shadow-md)',
		lg: 'var(--shadow-lg)'
	};
</script>

<div
	class="card {klass}"
	class:interactive
	class:source
	style="--pad:{pads[padding]}; --sh:{shadows[elevation]}"
>
	{@render children()}
</div>

<style>
	.card {
		background: var(--surface-card);
		border: 1.5px solid var(--border-default);
		border-radius: var(--radius-lg);
		box-shadow: var(--sh);
		padding: var(--pad);
		transition:
			box-shadow var(--duration-normal) var(--ease-out),
			transform var(--duration-normal) var(--ease-out);
	}
	.source {
		border-left: 3px solid var(--color-accent);
	}
	.interactive {
		cursor: pointer;
	}
	.interactive:hover {
		box-shadow: var(--shadow-md);
		transform: translateY(-2px);
	}
</style>
