// itaily-design-system/project/components/legal/ConfidenceMeter.jsx
import React from 'react';

/**
 * ConfidenceMeter — how grounded an AI answer is. Three-segment bar plus label.
 * Communicates that Itaily answers carry an explicit confidence, never blind certainty.
 */
export function ConfidenceMeter({ level = 'medium', showLabel = true, style = {}, ...rest }) {
  const map = {
    low:    { fill: 1, color: 'var(--status-danger-fg)', text: 'Low confidence' },
    medium: { fill: 2, color: 'var(--status-warning-fg)', text: 'Medium confidence' },
    high:   { fill: 3, color: 'var(--status-success-fg)', text: 'High confidence' },
  };
  const m = map[level] || map.medium;
  return (
    <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, fontFamily: 'var(--font-sans)', ...style }} {...rest}>
      <span style={{ display: 'inline-flex', gap: 3 }}>
        {[0, 1, 2].map((i) => (
          <span key={i} style={{
            width: 16, height: 6, borderRadius: 2,
            background: i < m.fill ? m.color : 'var(--neutral-200)',
          }} />
        ))}
      </span>
      {showLabel && (
        <span style={{ fontSize: 'var(--text-xs)', fontWeight: 'var(--weight-medium)', color: m.color }}>{m.text}</span>
      )}
    </div>
  );
}

// src/lib/components/ConfidenceMeter.svelte
<script lang="ts">
	// How grounded the AI output is. Numeric (0..1) → three-segment bar + label,
	// echoing the Itaily signature that an answer never feigns certainty.
	let {
		value = 0,
		showLabel = true,
		showPct = true
	}: { value?: number; showLabel?: boolean; showPct?: boolean } = $props();

	const pct = $derived(Math.round(value * 100));
	const level = $derived(value >= 0.8 ? 'high' : value >= 0.6 ? 'medium' : 'low');
	const color = $derived(
		level === 'high'
			? 'var(--status-success-fg)'
			: level === 'medium'
				? 'var(--status-warning-fg)'
				: 'var(--status-danger-fg)'
	);
	const fill = $derived(level === 'high' ? 3 : level === 'medium' ? 2 : 1);
	const label = $derived(
		level === 'high' ? 'High confidence' : level === 'medium' ? 'Medium confidence' : 'Low confidence'
	);
</script>

<span class="cm" style="--c:{color}">
	<span class="segs">
		{#each [0, 1, 2] as i (i)}
			<span class="seg" class:on={i < fill}></span>
		{/each}
	</span>
	{#if showLabel || showPct}
		<span class="lbl">
			{#if showLabel}{label}{/if}{#if showLabel && showPct} · {/if}{#if showPct}{pct}%{/if}
		</span>
	{/if}
</span>

<style>
	.cm {
		display: inline-flex;
		align-items: center;
		gap: 8px;
		font-family: var(--font-sans);
	}
	.segs {
		display: inline-flex;
		gap: 3px;
	}
	.seg {
		width: 16px;
		height: 6px;
		border-radius: 2px;
		background: var(--neutral-200);
	}
	.seg.on {
		background: var(--c);
	}
	.lbl {
		font-size: var(--text-xs);
		font-weight: var(--weight-medium);
		color: var(--c);
		white-space: nowrap;
	}
</style>
